### ISSUE TITLE
Drop-down text not visible in workspace-left-sidebar

### ISSUE THREAD

**Issue by swsjonathan** [behzadmoradi/laralack#4]
Both the foreground and background are white. Therefore the text is not visible

![admin_panel_bug_extended](https://user-images.githubusercontent.com/41731232/80321188-c271b780-8838-11ea-87b5-78b74dee4297.png)

**Comment by behzadmoradi** [comment]
Hi,
Thanks for reporting this issue. It`s fixed and merged into master branch.
